name: sync python api repo

on:
  workflow_dispatch:

jobs:
  checkout-python-api-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Checkout python api repo into samples directory
        uses: actions/checkout@v4
        with:
          repository: Esri/arcgis-python-api
          path: ${{ github.event.inputs.target_path }}

      - name: Access file from current repository
        run: |
          echo "Accessing the specific file: samples/02_power_users_developers/using_geocoding_geometry.ipynb"
          cat "${{ github.event.inputs.target_path }}/samples/02_power_users_developers/using_geocoding_geometry.ipynb"
